### PR TITLE
 fixed security flaw: files outside of web dir were allowed to be included (database.yml for example ...)

### PR DESCRIPTION
**Pull request by alex-pex**

### CODE REVIEW

**Comment by kevindew** [comment]
Thank you!

**Comment by kevindew** [comment]
Hi, I found that this broke symlinked assets (because realpath) resolves symlinks. I've wrote a quick patch that seems to fix that. Do you want to check that out?

**Comment by alex-pex** [comment]
I'll check that, I didn't think about symlink

**Comment by alex-pex** [comment]
for standard path (eg: use_stylesheet('/../config/databases.yml')) realpath and normalizePath return the same result
for symlinks, only normalizePath is useful

maybe you should drop realpath and only use normalizePath ?

**Comment by kevindew** [comment]
Hey, yeah I left both in so that the likelihood of this working on windows was higher. As I think the normalizePath method won't get a match on windows but they can't use the symlinks there so should only have to deal with the real_path approach. I'll have to get one of our windows based devs to check it out to be sure.

**Pull request merged**
